name: flake8 Lint

on: [ push, pull_request ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Install linter
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 ./app/ --count --max-complexity=15 --max-line-length=127 --statistics
